### ISSUE TITLE
Tiptap with Nuxt (without Vuetify)

### ISSUE THREAD

**Issue by connecteev** [iliyaZelenko/tiptap-vuetify-nuxt#2]
Thanks for creating this.

I've been looking for an integration of tiptap (which looks great) and Nuxt. Is there a way to do that without Vuetify (which is bloated and too much for my needs)? Does this repo allow that, and if so how can I get that working?

**Comment by iliyaZelenko** [comment]
Thank you for looking here. I noticed that I see your profile very often on a github, including in my projects. 😄 It looks like you write a lot in the Nuxt community as well.

I thought about not being dependent on a specific UI library, but it is actually very difficult. I would love to help if I could, unfortunately this cannot be done.
