### ISSUE TITLE
Cannot read property 'install' of undefined.

### ISSUE THREAD

**Issue by thebspin** [iliyaZelenko/tiptap-vuetify-nuxt#4]
Using nuxt 2.11.0 issue's start with this plugin. Locally whenever i do npm run dev it ends up in `Cannot read property 'install' of undefined`
I tried your example and changed nuxt to the latest version and that seems to be in some sort of bootloop now:

https://codesandbox.io/s/nuxt-tiptap-vuetify-03hzi

**Comment by ShisunXia** [comment]
Same here. I followed the documentation and I got 'Cannot read property 'install' of undefined'.

**Comment by iliyaZelenko** [comment]
I tried to solve this problem for a long time. To be honest, it's very strange. Despite my extensive experience with the Nuxt, I could not solve it. 

Later I will try to look at it again. I need help from other people.

**Comment by ShisunXia** [comment]
@iliyaZelenko Thanks for replying! I have downgraded the plugin to V2.7.0 and it worked perfectly. Also, I noticed that the momeory usage increased about 300MB after the plugin is loaded. Is this normal or it can be optimized as the plugin is only used on one page of the entire project?
Thanks in advance.

**Comment by arghaan** [comment]
I also encountered this problem and was able to solve it by replacing this

`plugins: [
  '~/plugins/TiptapVuetify'
],`

with this one

`plugins: [
        {src: '~/plugins/TiptapVuetify', mode: 'client'},
 ],`

**Comment by iliyaZelenko** [comment]
@arghaan Works. It is strange why I did not try it. Now works with the latest version. Thanks!
