### ISSUE TITLE
Help Needed - Question - How to show the loaded content to users?

### ISSUE THREAD

**Issue by rajesh-h** [iliyaZelenko/tiptap-vuetify-nuxt#5]
Hi,

This might be a basic question, but i am little puzzled.

Lat's say i created a blog post content using this package.

Now how do i show this content on the single post page which is visible to end users.

do I use  `<div v-html="MyPostContent">`  Vue/Nuxt warns us about not to use v-html. SO just wanted to know how do we actually show this data after posting.

**Comment by iliyaZelenko** [comment]
Hi,

Yes, you need to use `v-html` to display html. It can be used where necessary. Wherever it is dangerous to use, there are many explanations on the Internet why. To display the post fits perfectly.

You are receiving a warning from ESlint, this rule can be disabled globally or for this particular line of code.

**Comment by rajesh-h** [comment]
Thank you very much @iliyaZelenko 

Another question I have , do we have any option to use content as props?

I am currently using Editor.vue component in other components where i would like to overwrite content in different component.

Currently I am trying like below:
on Editor.vue
```
<tiptap-vuetify
      v-model="content"
      :extensions="extensions"
      placeholder="Write Your Content"
    />
```
```
props: {
    content: {
      type: String,
      default: ''
    }
  }
```
On My Other Component:

`<Editor :content="myNewHtml" />`
```
import Editor from '@/components/Editor'
data: () => ({ myNewHtml: ''})
```

This is currenty throwing error as I cannot mutate props directly.

**Comment by rajesh-h** [comment]
Here is the sandbox if it is going to help.
https://codesandbox.io/s/nuxt-tiptap-vuetify-7fogz

**Comment by rajesh-h** [comment]
If you ask me why I am doing this way is.

I have a 
Editor.vue
MultipleEditor.vue - This calls Editor.vue with option to add multiple Editor on click of button, and the text entered gets stored on a list.

FinalIndex.vue - this calls MultipleEditor.vue

In case you need a complete example I can create a sandbox for it.

Thank you very much

**Comment by iliyaZelenko** [comment]
You need a vue pattern called "Transparent Wrapper", its a common pattern for Vue devs. For example, you can read [this ](https://zendev.com/2018/05/31/transparent-wrapper-components-in-vue.html) article.

I have [modified your sandbox](https://codesandbox.io/s/nuxt-tiptap-vuetify-ehili) according to this pattern. Key code are: `v-model="myNewHtml"`, `:value="value"`, `@input="$emit('input', arguments[0])"`.

I think you understand this guy, he is very useful and not so complicated.

**Comment by rajesh-h** [comment]
Thank you for the above. I am still busy on it I will provide feedback on the same.
